application:
  timeout:
    read: 1000
    write: 1000
  port: 8787
  host: "localhost"
  mode: "debug"
  appId: "go"
  apiBaseRoute: "/api"
  cors:
    allowOrigins: ["http://localhost:3000"]

redis:
  host: "127.0.0.1:6379"
  password: ""
  db: 0