version: '3.8'

services:
  app:
    build: 
      context: .
    ports:
      - "8787:8787"
    networks:
      - proxy-server

  redis:
    container_name: "redis"
    image: redislabs/rejson
    ports:
      - "6379:6379"
    networks:
      - proxy-server

networks:
  proxy-server:
    driver: bridge